"""A student whose target layer is *itself* multiplicative (a Sigma-Pi block).

This is the substrate for the "Sigma-Pi student" further-work experiment. Where
:class:`CNNStudent` has an ordinary additive ``conv1`` that a teacher repairs,
:class:`SigmaPiStudent` places a :class:`~polyweave.layers.sigmapi_conv.ConvSigmaPi2d`
block right after a fixed stem, and the teacher generates *its* two convolutional
weight matrices (see :class:`~polyweave.targets.SigmaPiConvTargetSpec`).

The recruitment hypothesis predicts the teacher's own pi branch should fire most
strongly here, because the target mapping is now explicitly higher-order. The
block's ``pi_scale`` gate is left learnable on the student so its recruitment can
be measured independently of the teacher's.

Pipeline (channels-preserving block):

    x -> stem(in_ch -> width) -> ConvSigmaPi2d(width) -> pool -> trunk -> fc
                                  ^ teacher-generated weights install here
"""

from __future__ import annotations

from typing import Dict, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..layers.sigmapi_conv import ConvSigmaPi2d
from ..ops.signed_log import signed_log

GeneratedSigmaPi = Dict[str, torch.Tensor]
# {"sigma_weight","sigma_bias","pi_weight","pi_bias"} — see SigmaPiConvTargetSpec.


class SigmaPiStudent(nn.Module):
    """A classifier with a generated multiplicative (Sigma-Pi) target block.

    Args:
        width: channel width of the stem output and the Sigma-Pi block
            (the block is channels-preserving, so this is the generated target width).
        num_classes: number of output classes.
        in_ch: input image channels (3 for CIFAR-like data).
        kernel_size: kernel size of both the stem and the Sigma-Pi block.
        img_size: spatial size of the (square) input, used to size the head.
    """

    def __init__(
        self,
        width: int = 32,
        num_classes: int = 10,
        in_ch: int = 3,
        kernel_size: int = 3,
        img_size: int = 32,
    ) -> None:
        super().__init__()
        self.width = width
        self.num_classes = num_classes
        self.in_ch = in_ch
        self.kernel_size = kernel_size
        self.img_size = img_size
        padding = kernel_size // 2

        # Fixed stem maps input channels up to the block width.
        self.stem = nn.Sequential(
            nn.Conv2d(in_ch, width, kernel_size, padding=padding),
            nn.BatchNorm2d(width),
            nn.ReLU(),
        )
        # The multiplicative target block (weights generated by the teacher).
        self.sigmapi = ConvSigmaPi2d(width, kernel_size=kernel_size, padding=padding)
        self.pool = nn.AdaptiveAvgPool2d((4, 4))
        self.fc = nn.Linear(width * 4 * 4, num_classes)

    def _apply_sigmapi(
        self, h: torch.Tensor, gen: Optional[GeneratedSigmaPi]
    ) -> torch.Tensor:
        if gen is None:
            return self.sigmapi(h)
        # Functional Sigma-Pi forward using the *generated* conv weights so
        # gradients flow back to the teacher, while ``pi_scale`` and ``bn`` stay
        # the student's own learnable parameters (mirrors ConvSigmaPi2d.forward).
        block = self.sigmapi
        pad = self.kernel_size // 2
        sigma = F.conv2d(
            h - h.mean(dim=(-2, -1), keepdim=True),
            gen["sigma_weight"], gen["sigma_bias"], padding=pad,
        )
        z = signed_log(h, block.eps)
        pi = torch.exp(block.pi_scale) * torch.tanh(
            F.conv2d(z, gen["pi_weight"], gen["pi_bias"], padding=pad)
        )
        return F.relu(block.bn(sigma + pi))

    def extract_features(
        self, x: torch.Tensor, gen_sigmapi: Optional[GeneratedSigmaPi] = None
    ) -> torch.Tensor:
        h = self.stem(x)
        h = self._apply_sigmapi(h, gen_sigmapi)
        return torch.flatten(self.pool(h), 1)

    def forward(
        self, x: torch.Tensor, gen_sigmapi: Optional[GeneratedSigmaPi] = None
    ) -> torch.Tensor:
        return self.fc(self.extract_features(x, gen_sigmapi))

    @torch.no_grad()
    def pi_scale_mean(self) -> float:
        """Recruitment diagnostic of the student's own Sigma-Pi block."""
        return self.sigmapi.pi_scale_mean()
